### ISSUE TITLE
Parts List

### ISSUE THREAD

**Issue by bertramt** [CANBus-Triple/CANBus-Triple-Hardware#2]
Would it be possible to get a parts list in csv format that could be imported into Digikey?

**Comment by etx** [comment]
Hey Tim! Here is the BOM:

https://docs.google.com/spreadsheets/d/1azboeqHcyEtHBtjf19RNIPin-HeI7VY-TuqwQfGxV1k/edit?usp=drive_web

**Comment by bertramt** [comment]
Thank you for your reply!

Any chance you could commit that to the repo so it's always easy to find?

**Comment by etx** [comment]
No problem! 

I just re-verified the Digikey BOM parts and exported the BOM to a CSV file that you can import in. Find it here:
https://github.com/CANBus-Triple/CANBus-Triple-Hardware/blob/master/CBT-RevF-DigikeyBOM.csv

I wish they had an easier way to share the BOM. :(

**Comment by bertramt** [comment]
At least the CSV is functional and better than nothing.  Thank You for you help.

**Comment by jackm** [comment]
It appears as though you are missing some parts in the BOM. For example, I don't see a part for the 12 position right-angle 0.1" header to connect to the external CAN bus lines.
